export const GET_ALL_NEWS = 'GET_ALL_NEWS';
export const GET_LATEST_NEWS = 'GET_LATEST_NEWS';
export const GET_NEWS_BY_CATEGORY = 'GET_NEWS_BY_CATEGORY';
export const GET_DETAIL_OF_NEWS = 'GET_DETAIL_OF_NEWS';
export const ADD_NEWS = 'ADD_NEWS';
export const DELETE_NEWS = 'DELETE_NEWS';
export const UPDATE_NEWS = 'UPDATE_NEWS';
export const EDIT_NEWS = 'EDIT_NEWS';
export const GET_EDIT_STATUS = 'GET_EDIT_STATUS';
export const GET_ALL_NEWS_PAGNIATION = 'GET_ALL_NEWS_PAGNIATION';
export const GET_TRENDING_NEWS = 'GET_TRENDING_NEWS';

// export const RESET_STATE = 'RESET_STATE';